import {test,before,after,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {serveStaticAsset} from './static-assets.mjs';
import {historyFixture,historyPaged} from './tw-history-fixture.mjs';
import {twFixture} from './tw-stocks-fixture.mjs';
import {englishPage} from './locale-browser.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');
let browser,server,base,page,requests,errors;
before(async()=>{server=createServer(serveStaticAsset);await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});});
after(async()=>{await browser.close();await new Promise(r=>server.close(r));});
const requested=u=>({startDate:u.searchParams.get('startDate'),endDate:u.searchParams.get('endDate'),limit:Number(u.searchParams.get('limit')),offset:Number(u.searchParams.get('offset'))});
beforeEach(async()=>{page=await englishPage(browser);await page.addInitScript(()=>{const original=window.fetch.bind(window);window.fetch=(url,options)=>String(url).startsWith('/api/tw/history')?original(url,{...options,signal:undefined}):original(url,options);});requests=[];errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',r=>{const u=new URL(r.request().url());requests.push(u);const p=u.pathname==='/api/tw/history'?historyFixture(requested(u)):u.pathname==='/api/tw/stocks'?twFixture(u.searchParams.get('date')):u.pathname==='/api/history'?{from:u.searchParams.get('from'),to:u.searchParams.get('to'),jobs:[]}:u.pathname==='/api/runner/executions'?{status:'NOT_CONFIGURED',jobs:[],warnings:[]}:u.pathname==='/api/settings/job-metadata'?{version:1,revision:'0',overrides:{},warning:null}:{collectionStatus:'NOT_CONFIGURED',collectedAt:new Date().toISOString(),jobs:[],errors:[],warnings:[],unmatchedIncludes:[]};return r.fulfill({contentType:'application/json',body:JSON.stringify(p)});});});
afterEach(async()=>{await page.close();assert.deepEqual(errors,[]);});
const count=path=>requests.filter(u=>u.pathname===path).length;
const historyCount=()=>count('/api/tw/history');
const ready=()=>page.waitForFunction(()=>document.getElementById('twHistoryPanel').getAttribute('aria-busy')==='false');
async function open(width=1280){await page.setViewportSize({width,height:900});await page.goto(base+'/#tw');await page.waitForFunction(()=>document.getElementById('twStatus').textContent.includes('COHERENT'));assert.equal(historyCount(),0);await page.locator('#twHistoryTab').click();await ready();}
for(const width of [1280,375,320])test('History actual facts and keyboard without overflow at '+width,async()=>{await open(width);assert.equal(await page.locator('.tw-history-observation').count(),2);const body=await page.locator('#twHistoryPanel').innerText();assert.match(body,/PARTIAL/);assert.match(body,/WARMING_UP/);assert.match(body,/Zero candidates.*does not mean no anomaly/);assert.match(body,/tw-daily:/);assert.match(body,/SUCCESS/);assert.match(body,/TWSE/);assert.match(body,/TPEX/);assert.match(await page.locator('#twHistoryPage').innerText(),/Offset 0.*2 rows.*total unknown/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);await page.locator('#twCurrentTab').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#twCurrentPanel').isVisible(),true);await page.locator('#twHistoryTab').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#twHistoryPanel').isVisible(),true);assert.equal(historyCount(),1);assert.equal(count('/api/reports/tw/detail'),0);await page.locator('#twHistoryPanel').screenshot({path:process.env.HISTORY_SCREENSHOT_ROOT?process.env.HISTORY_SCREENSHOT_ROOT+'/history-'+width+'.png':undefined});});
test('five states and null UNKNOWN remain distinct, failure clears stale',async()=>{await open();for(const state of ['PARTIAL','EMPTY','UNAVAILABLE','ERROR']){await page.route('**/api/tw/history?*',r=>{const u=new URL(r.request().url());requests.push(u);return r.fulfill({contentType:'application/json',body:JSON.stringify(historyFixture(requested(u),state))});});await page.locator('#twHistoryRefresh').click();await ready();assert.match(await page.locator('#twHistoryStatus').innerText(),new RegExp(state));assert.equal(await page.locator('.tw-history-observation').count(),state==='PARTIAL'?2:0);if(state==='PARTIAL')assert.match(await page.locator('#twHistoryRows').innerText(),/UNKNOWN.*not 0/);}
await page.route('**/api/tw/history?*',r=>r.fulfill({status:503,body:'C:/private/db stderr'}));await page.locator('#twHistoryRefresh').click();await ready();assert.equal(await page.locator('.tw-history-observation').count(),0);assert.doesNotMatch(await page.locator('#twHistoryPanel').innerText(),/private|stderr/);});
test('bad dates and367 reject before fetch,366 accepted and new query resets offset',async()=>{await open();for(const [start,end]of [['2024-01-01','2025-01-01'],['2026-02-29','2026-03-01'],['2026-09-25','2026-09-24'],['0000-01-01','2026-09-25']]){await page.locator('#twHistoryStart').fill(start);await page.locator('#twHistoryEnd').fill(end);const n=historyCount();await page.locator('#twHistoryFilter button[type=submit]').click();assert.equal(historyCount(),n);assert.match(await page.locator('#twHistoryValidation').innerText(),/366 inclusive/);}await page.locator('#twHistoryStart').fill('2024-01-01');await page.locator('#twHistoryEnd').fill('2024-12-31');await page.locator('#twHistoryFilter button[type=submit]').click();await ready();assert.match(await page.locator('#twHistoryStatus').innerText(),/READY/);assert.equal(await page.locator('.tw-history-observation').count(),2);assert.equal(requests.filter(u=>u.pathname==='/api/tw/history').at(-1).searchParams.get('offset'),'0');});
test('Refresh only History, pagination one bounded page and no automatic detail',async()=>{await page.route('**/api/tw/history?*',r=>{const u=new URL(r.request().url());requests.push(u);return r.fulfill({contentType:'application/json',body:JSON.stringify(historyPaged(requested(u)))});});await open();const stocks=count('/api/tw/stocks');await page.locator('#twHistoryNext').click();await ready();assert.match(await page.locator('#twHistoryPage').innerText(),/Offset 20/);assert.equal(historyCount(),2);await page.locator('#twHistoryPrevious').click();await ready();assert.match(await page.locator('#twHistoryPage').innerText(),/Offset 0/);assert.equal(historyCount(),3);await page.locator('#twHistoryRefresh').click();await ready();assert.equal(count('/api/tw/stocks'),stocks);assert.equal(count('/api/reports/tw/detail'),0);assert.equal(historyCount(),4);await page.locator('#overviewPage').click();await page.locator('#twPage').click();assert.equal(historyCount(),4);await page.waitForTimeout(1100);assert.equal(historyCount(),4);});
test('locale held render preserves inputs,offset,rows,focus and zero API calls',async()=>{await page.route('**/api/tw/history?*',r=>{const u=new URL(r.request().url());requests.push(u);return r.fulfill({contentType:'application/json',body:JSON.stringify(historyPaged(requested(u)))});});await open();await page.locator('#twHistoryNext').click();await ready();await page.locator('#twHistoryStart').fill('2026-08-01');await page.locator('#twHistoryStart').focus();const n=requests.length;const before=await page.locator('.tw-history-observation').count();await page.evaluate(async()=>{const i=await import('/ui/i18n.mjs');i.setLocale('zh-TW');});assert.equal(requests.length,n);assert.equal(await page.locator('#twHistoryStart').inputValue(),'2026-08-01');assert.equal(await page.locator('#twHistoryStart').evaluate(n=>n===document.activeElement),true);assert.match(await page.locator('#twHistoryPage').innerText(),/位移 20/);assert.equal(await page.locator('.tw-history-observation').count(),before);assert.match(await page.locator('#twHistoryRows').innerText(),/保存候選數/);await page.evaluate(async()=>{const i=await import('/ui/i18n.mjs');i.setLocale('en');});assert.equal(requests.length,n);assert.match(await page.locator('#twHistoryRows').innerText(),/Saved candidate count/);});
test('latest matching range wins, leaving subpage or primary page suppresses stale response',async()=>{await open();let release;const held=new Promise(r=>release=r);await page.route('**/api/tw/history?*',async r=>{const u=new URL(r.request().url());requests.push(u);if(u.searchParams.get('endDate')!=='2026-09-24')await held;await r.fulfill({contentType:'application/json',body:JSON.stringify(historyFixture(requested(u)))}).catch(()=>{});});await page.locator('#twHistoryRefresh').click();await page.waitForFunction(()=>document.getElementById('twHistoryPanel').getAttribute('aria-busy')==='true');await page.locator('#twHistoryStart').fill('2026-09-21');await page.locator('#twHistoryEnd').fill('2026-09-24');await page.locator('#twHistoryFilter button[type=submit]').click();await ready();release();assert.match(await page.locator('#twHistoryRows').innerText(),/2026-09-24/);assert.doesNotMatch(await page.locator('#twHistoryRows').innerText(),new RegExp(new Date().toISOString().slice(0,10)));
await page.unroute('**/api/tw/history?*');for(const leave of ['#twCurrentTab','#overviewPage']){let finish;const wait=new Promise(r=>finish=r);await page.route('**/api/tw/history?*',async r=>{await wait;const u=new URL(r.request().url());await r.fulfill({contentType:'application/json',body:JSON.stringify(historyFixture(requested(u)))}).catch(()=>{});});await page.locator('#twHistoryRefresh').click();await page.waitForFunction(()=>document.getElementById('twHistoryPanel').getAttribute('aria-busy')==='true');await page.locator(leave).click();finish();assert.equal(await page.locator('.tw-history-observation').count(),0);await page.unroute('**/api/tw/history?*');if(leave==='#twCurrentTab'){await page.locator('#twHistoryTab').click();await ready();}}});
test('duplicate Refresh deduplicates pending read',async()=>{await open();let release;const held=new Promise(r=>release=r);await page.route('**/api/tw/history?*',async r=>{const u=new URL(r.request().url());requests.push(u);await held;await r.fulfill({contentType:'application/json',body:JSON.stringify(historyFixture(requested(u)))});});const n=historyCount();await page.locator('#twHistoryRefresh').click();await page.waitForFunction(()=>document.getElementById('twHistoryPanel').getAttribute('aria-busy')==='true');await page.locator('#twHistoryRefresh').click();assert.equal(historyCount(),n+1);release();await ready();});
