import {test,before,after,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {mkdir} from 'node:fs/promises';
import {serveStaticAsset} from './static-assets.mjs';
import {twPerformanceFixture,twPerformanceItem} from './tw-performance-fixture.mjs';
import {performanceFixture} from './performance-fixture.mjs';
import {englishPage} from './locale-browser.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');
let browser,server,base,page,requests,errors;
before(async()=>{server=createServer(serveStaticAsset);await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});if(process.env.TW_PERFORMANCE_SCREENSHOT_ROOT)await mkdir(process.env.TW_PERFORMANCE_SCREENSHOT_ROOT,{recursive:true});});
after(async()=>{await browser.close();await new Promise(r=>server.close(r));});
const requested=u=>({startDate:u.searchParams.get('startDate'),endDate:u.searchParams.get('endDate'),limit:Number(u.searchParams.get('limit')),offset:Number(u.searchParams.get('offset'))});
function fixture(q,state='PARTIAL',paged=false){
 const item=twPerformanceItem({targetDate:q.endDate});item.horizons[1].returnPercent=-7.5;
 Object.assign(item.horizons[2],{state:'NOT_YET_DUE',reasonCode:'SESSION_NOT_YET_DUE',close:null,returnPercent:null,provenance:null});
 Object.assign(item.horizons[3],{state:'CALENDAR_UNAVAILABLE',reasonCode:'CALENDAR_COVERAGE_INSUFFICIENT',expectedDate:null,dueAt:null,close:null,returnPercent:null,provenance:null});
 Object.assign(item.horizons[4],{state:'PRICE_UNAVAILABLE',reasonCode:'OFFICIAL_PRICE_MISSING',close:null,returnPercent:null,provenance:null});
 const second=twPerformanceItem({targetDate:q.endDate,runId:'b'.repeat(32),referenceState:'PRICE_UNAVAILABLE',referenceReasonCode:'REFERENCE_CLOSE_UNAVAILABLE',referenceClose:null,referenceProvenance:null});
 second.horizons.forEach(h=>Object.assign(h,{state:'PRICE_UNAVAILABLE',reasonCode:'REFERENCE_CLOSE_UNAVAILABLE',returnPercent:null}));
 const items=['EMPTY','UNAVAILABLE','ERROR'].includes(state)?[]:paged?Array.from({length:q.limit},(_,i)=>twPerformanceItem({targetDate:q.endDate,symbol:String(1000+i),runId:(q.offset===0?'a':'b').repeat(32)})):[item,second];
 const more=paged && !['EMPTY','UNAVAILABLE','ERROR'].includes(state);
 return twPerformanceFixture(state,{query:{requestedStartDate:q.startDate,requestedEndDate:q.endDate,limit:q.limit,offset:q.offset},scope:{startDate:'2020-01-01'},items,page:['UNAVAILABLE','ERROR'].includes(state)?null:{limit:q.limit,offset:q.offset,returned:items.length,hasMore:more,nextOffset:more?q.offset+q.limit:null,total:null}});
}
beforeEach(async()=>{page=await englishPage(browser);await page.addInitScript(()=>{const original=window.fetch.bind(window);window.fetch=(url,options)=>String(url).startsWith('/api/tw/performance')?original(url,{...options,signal:undefined}):original(url,options);});requests=[];errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',r=>{const u=new URL(r.request().url());requests.push(u);const p=u.pathname==='/api/tw/performance'?fixture(requested(u)):u.pathname.startsWith('/api/performance/')?performanceFixture(u):u.pathname==='/api/history'?{from:u.searchParams.get('from'),to:u.searchParams.get('to'),jobs:[]}:u.pathname==='/api/runner/executions'?{status:'NOT_CONFIGURED',jobs:[],warnings:[]}:u.pathname==='/api/settings/job-metadata'?{version:1,revision:'0',overrides:{},warning:null}:{collectionStatus:'NOT_CONFIGURED',collectedAt:new Date().toISOString(),jobs:[],errors:[],warnings:[],unmatchedIncludes:[]};return r.fulfill({contentType:'application/json',body:JSON.stringify(p)});});});
afterEach(async()=>{await page.close();assert.deepEqual(errors,[]);});
const count=path=>requests.filter(u=>u.pathname===path).length;
const twCount=()=>count('/api/tw/performance'),usCount=()=>requests.filter(u=>u.pathname.startsWith('/api/performance/')).length;
const ready=()=>page.waitForFunction(()=>document.getElementById('twPerformancePanel').getAttribute('aria-busy')==='false');
async function open(width=1280){await page.setViewportSize({width,height:900});await page.goto(base+'/#performance');await page.waitForFunction(()=>document.getElementById('performanceListStatus').textContent.includes('READY'));assert.equal(twCount(),0);await page.locator('#performanceTwTab').click();await ready();}
for(const width of [1280,375,320])test('Taiwan source facts, keyboard and no overflow at '+width,async()=>{
 await open(width);assert.equal(await page.locator('.tw-performance-observation').count(),2);
 const text=await page.locator('#twPerformancePanel').innerText();for(const code of ['0%','-7.5%','NOT_YET_DUE','CALENDAR_UNAVAILABLE','PRICE_UNAVAILABLE','13:33','tw-candidate:','CURRENT_SAVED_OFFICIAL_CLOSE_RESEARCH_EVIDENCE'])assert.ok(text.includes(code),code);
 assert.match(text,/Reference official close.*not entry price/);assert.match(text,/historicalPIT=false/);
 assert.equal(await page.locator('.tw-performance-horizon').count(),10);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);
 const n=twCount(),us=usCount();await page.locator('#performanceUsTab').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#performanceUsPanel').isVisible(),true);await page.locator('#performanceTwTab').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#twPerformancePanel').isVisible(),true);assert.equal(twCount(),n);assert.equal(usCount(),us);
 if(process.env.TW_PERFORMANCE_SCREENSHOT_ROOT)for(const locale of ['en','zh-TW']){await page.evaluate(async l=>(await import('/ui/i18n.mjs')).setLocale(l),locale);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);await page.screenshot({path:process.env.TW_PERFORMANCE_SCREENSHOT_ROOT+'/taiwan-'+locale+'-'+width+'.png',fullPage:true});await page.screenshot({path:process.env.TW_PERFORMANCE_SCREENSHOT_ROOT+'/taiwan-top-'+locale+'-'+width+'.png'});}
});
test('all five states, failed or private output clears stale data',async()=>{await open();for(const state of ['READY','PARTIAL','EMPTY','UNAVAILABLE','ERROR']){await page.route('**/api/tw/performance?*',r=>{const u=new URL(r.request().url());requests.push(u);return r.fulfill({contentType:'application/json',body:JSON.stringify(fixture(requested(u),state))});});await page.locator('#twPerformanceRefresh').click();await ready();assert.match(await page.locator('#twPerformanceStatus').innerText(),new RegExp(state));assert.equal(await page.locator('.tw-performance-observation').count(),['READY','PARTIAL'].includes(state)?2:0);}
 await page.route('**/api/tw/performance?*',r=>{const p=fixture(requested(new URL(r.request().url())));p.private='C:/private/db stderr';return r.fulfill({contentType:'application/json',body:JSON.stringify(p)});});await page.locator('#twPerformanceRefresh').click();await ready();assert.equal(await page.locator('.tw-performance-observation').count(),0);assert.doesNotMatch(await page.locator('#twPerformancePanel').innerText(),/private|stderr/);
 await page.route('**/api/tw/performance?*',r=>r.fulfill({status:503,body:'C:/private/db stderr'}));await page.locator('#twPerformanceRefresh').click();await ready();assert.equal(await page.locator('.tw-performance-observation').count(),0);
});
test('invalid dates and367 reject before reads;366 allowed',async()=>{await open();for(const [start,end]of [['2024-01-01','2025-01-01'],['2026-02-29','2026-03-01'],['2026-09-25','2026-09-24'],['0000-01-01','2026-10-01']]){await page.locator('#twPerformanceStart').fill(start);await page.locator('#twPerformanceEnd').fill(end);const n=twCount();await page.locator('#twPerformanceFilter button[type=submit]').click();assert.equal(twCount(),n);assert.match(await page.locator('#twPerformanceValidation').innerText(),/366 inclusive/);}await page.locator('#twPerformanceStart').fill('2024-01-01');await page.locator('#twPerformanceEnd').fill('2024-12-31');await page.locator('#twPerformanceFilter button[type=submit]').click();await ready();assert.equal(await page.locator('.tw-performance-observation').count(),2);assert.equal(requests.filter(u=>u.pathname==='/api/tw/performance').at(-1).searchParams.get('offset'),'0');});
test('paging, Refresh, cached subviews and reentry; Taiwan makes no US reads',async()=>{await page.route('**/api/tw/performance?*',r=>{const u=new URL(r.request().url());requests.push(u);return r.fulfill({contentType:'application/json',body:JSON.stringify(fixture(requested(u),'READY',true))});});await open();const us=usCount();await page.locator('#twPerformanceNext').click();await ready();assert.match(await page.locator('#twPerformancePage').innerText(),/Offset 20/);assert.equal(twCount(),2);await page.locator('#performanceUsTab').click();await page.locator('#performanceTwTab').click();assert.match(await page.locator('#twPerformancePage').innerText(),/Offset 20/);assert.equal(twCount(),2);await page.locator('#twPerformancePrevious').click();await ready();await page.locator('#twPerformanceRefresh').click();await ready();assert.equal(twCount(),4);await page.locator('#overviewPage').click();await page.locator('#performancePage').click();await ready();assert.equal(twCount(),4);assert.equal(usCount(),us);await page.waitForTimeout(1100);assert.equal(twCount(),4);});
test('locale changes preserve focus, inputs, page and rows with zero reads',async()=>{await page.route('**/api/tw/performance?*',r=>{const u=new URL(r.request().url());requests.push(u);return r.fulfill({contentType:'application/json',body:JSON.stringify(fixture(requested(u),'READY',true))});});await open();await page.locator('#twPerformanceNext').click();await ready();await page.locator('#twPerformanceStart').fill('2026-08-01');await page.locator('#twPerformanceStart').focus();const n=requests.length;for(const locale of ['zh-TW','en']){await page.evaluate(async l=>(await import('/ui/i18n.mjs')).setLocale(l),locale);assert.equal(requests.length,n);assert.equal(await page.locator('#twPerformanceStart').inputValue(),'2026-08-01');assert.equal(await page.locator('#twPerformanceStart').evaluate(n=>n===document.activeElement),true);assert.equal(await page.locator('.tw-performance-observation').count(),20);}assert.match(await page.locator('#twPerformancePage').innerText(),/Offset 20/);});
test('latest matching range wins; leaving source or primary suppresses stale reads',async()=>{await open();let release;const held=new Promise(r=>release=r);await page.route('**/api/tw/performance?*',async r=>{const u=new URL(r.request().url());requests.push(u);if(u.searchParams.get('endDate')!=='2026-09-24')await held;await r.fulfill({contentType:'application/json',body:JSON.stringify(fixture(requested(u)))}).catch(()=>{});});await page.locator('#twPerformanceRefresh').click();await page.waitForFunction(()=>document.getElementById('twPerformancePanel').getAttribute('aria-busy')==='true');await page.locator('#twPerformanceStart').fill('2026-09-21');await page.locator('#twPerformanceEnd').fill('2026-09-24');await page.locator('#twPerformanceFilter button[type=submit]').click();await ready();release();assert.match(await page.locator('#twPerformanceRows').innerText(),/2026-09-24/);await page.unroute('**/api/tw/performance?*');
 for(const leave of ['#performanceUsTab','#overviewPage']){let finish;const wait=new Promise(r=>finish=r);await page.route('**/api/tw/performance?*',async r=>{await wait;await r.fulfill({contentType:'application/json',body:JSON.stringify(fixture(requested(new URL(r.request().url()))))}).catch(()=>{});});await page.locator('#twPerformanceRefresh').click();await page.waitForFunction(()=>document.getElementById('twPerformancePanel').getAttribute('aria-busy')==='true');await page.locator(leave).click();finish();assert.equal(await page.locator('.tw-performance-observation').count(),0);await page.unroute('**/api/tw/performance?*');if(leave==='#performanceUsTab'){await page.locator('#performanceTwTab').click();await ready();}}
});
test('pending Refresh deduplicates and reenter resumes one canceled load',async()=>{await open();let release;const held=new Promise(r=>release=r);await page.route('**/api/tw/performance?*',async r=>{const u=new URL(r.request().url());requests.push(u);await held;await r.fulfill({contentType:'application/json',body:JSON.stringify(fixture(requested(u)))}).catch(()=>{});});const n=twCount();await page.locator('#twPerformanceRefresh').click();await page.waitForFunction(()=>document.getElementById('twPerformancePanel').getAttribute('aria-busy')==='true');await page.locator('#twPerformanceRefresh').click();assert.equal(twCount(),n+1);await page.locator('#performanceUsTab').click();release();await page.unroute('**/api/tw/performance?*');await page.locator('#performanceTwTab').click();await ready();assert.equal(twCount(),n+2);});
