import { englishPage } from './locale-browser.mjs';
import {test,before,after,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {mkdir} from 'node:fs/promises';
import {serveStaticAsset} from './static-assets.mjs';
import {reportsFixture,reportDetailFixture} from './reports-fixture.mjs';
import {twReportsFixture,twDetailFixture} from './tw-reports-fixture.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');let browser,server,base,page,errors,requests;
before(async()=>{server=createServer(serveStaticAsset);await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});await mkdir('.tools/tw-reports/visual',{recursive:true});});
after(async()=>{await browser.close();await new Promise(r=>server.close(r));});
beforeEach(async()=>{page=await englishPage(browser);errors=[];requests=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',route=>{const url=new URL(route.request().url());requests.push(url);const p=url.pathname==='/api/reports/tw'?twReportsFixture(url):url.pathname==='/api/reports/tw/detail'?twDetailFixture(url):url.pathname==='/api/reports/us-insider'?reportsFixture(url):url.pathname==='/api/reports/us-insider/detail'?reportDetailFixture(url):url.pathname==='/api/settings/job-metadata'?{version:1,revision:'0',overrides:{},warning:null}:{collectionStatus:'NOT_CONFIGURED',status:'NOT_CONFIGURED',collectedAt:new Date().toISOString(),jobs:[],errors:[],warnings:[],unmatchedIncludes:[]};return route.fulfill({contentType:'application/json',body:JSON.stringify(p)});});});
afterEach(async()=>{await page.close();assert.deepEqual(errors,[]);});
const ready=type=>page.waitForFunction(type=>['READY','PARTIAL','EMPTY','UNAVAILABLE','ERROR'].some(s=>document.getElementById(`tw${type}-Status`).textContent.startsWith(s)),type);
const detail=()=>page.waitForFunction(()=>document.getElementById('twReportStatus').textContent.includes('PARTIAL'));
const open=async(width=1280)=>{await page.setViewportSize({width,height:900});await page.goto(`${base}/#reports`);await Promise.all(['daily','weekly'].map(ready));await page.waitForFunction(()=>document.getElementById('reportsStatus').textContent.includes("READY"));};
for(const width of [1280,375,320])test(`three families, safe TW daily/weekly detail and real keyboard at ${width}`,async()=>{
  await open(width);assert.equal(await page.locator('.report-card').count(),20);for(const type of ['daily','weekly'])assert.equal(await page.locator(`#tw${type}-Rows .tw-report-card`).count(),20);
  assert.match(await page.locator('#twdaily-Status').innerText(),/^PARTIAL/);assert.match(await page.locator('#twweekly-Status').innerText(),/^READY/);assert.match(await page.locator('#twweekly-Rows').innerText(),/FAILED/);assert.match(await page.locator('#twReportsLimits').innerText(),/UNKNOWN is not NO/);
  for(const type of ['daily','weekly']){
    await page.locator(`[data-reports-page=tw-${type}]`).click();await ready(type);assert.equal(await page.locator('#reportsConnected').isVisible(),false);
    let found=false;for(let i=0;i<50;i++){await page.keyboard.press('Tab');found=await page.evaluate(()=>document.activeElement?.classList.contains('tw-report-open'));if(found)break;}assert.ok(found);const opener=await page.evaluate(()=>document.activeElement.textContent);await page.keyboard.press(type==='daily'?'Space':'Enter');await detail();assert.equal(await page.locator('#twReportClose').evaluate(n=>n===document.activeElement),true);
    assert.match(await page.locator('#twReportFacts').innerText(),type==='daily'?/null \(unknown, not 0 \/ NO\)/:/100 records exported/);assert.match(await page.locator('#twReportMetadata').innerText(),type==='daily'?/WARMING_UP/:/164/);assert.equal(await page.locator('#twReportBody script,#twReportBody a,#twReportBody img').count(),0);assert.equal(await page.evaluate(()=>globalThis.twReportPwned),undefined);assert.match(await page.locator('#twReportBody').innerText(),/<script>/);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);assert.equal(await page.locator('#twReportDetail').evaluate(n=>n.scrollWidth<=n.clientWidth),true);
    await page.screenshot({path:`.tools/tw-reports/visual/${type}-detail-${width}.png`});await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.textContent),opener);
    await page.locator(`#tw${type}-Next`).click();await ready(type);assert.match(await page.locator(`#tw${type}-Page`).innerText(),/offset 20/);assert.equal(await page.locator(`#tw${type}-Rows .tw-report-card`).count(),1);await page.locator(`#tw${type}-Previous`).click();await ready(type);assert.equal(await page.locator(`#tw${type}-Rows .tw-report-card`).count(),20);
  }
});
test('one All source failure preserves the other two, and stale contents clear on failures',async()=>{
  await page.route('**/api/reports/tw?*',r=>{const u=new URL(r.request().url());return r.fulfill({contentType:'application/json',body:JSON.stringify(twReportsFixture(u,u.searchParams.get('type')==='weekly'?'ERROR':'PARTIAL'))});});await open();assert.match(await page.locator('#twweekly-Status').innerText(),/^ERROR/);assert.equal(await page.locator('.report-card').count(),20);assert.equal(await page.locator('#twdaily-Rows .tw-report-card').count(),20);assert.equal(await page.locator('#twweekly-Rows .tw-report-card').count(),0);
  for(const state of ['UNAVAILABLE','EMPTY','ERROR']){await page.route('**/api/reports/tw?*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(twReportsFixture(new URL(r.request().url()),state))}));await page.locator('#twdaily-Reload').click();await page.waitForFunction(s=>document.getElementById('twdaily-Status').textContent.startsWith(s),state);assert.equal(await page.locator('#twdaily-Rows .tw-report-card').count(),0);assert.equal(await page.locator('.report-card').count(),20);}
});
test('pending refresh cancels old presentation and newest response wins while slow All source stays independent',async()=>{
  let release,started=0;const held=new Promise(r=>release=r);await page.route('**/api/reports/tw?*',async r=>{const u=new URL(r.request().url());const first=u.searchParams.get('type')==='daily'&&++started===1;if(first)await held;const p=twReportsFixture(u);if(u.searchParams.get('type')==='daily')p.items[0].classificationStatus=first?'UNKNOWN':'WARMING_UP';await r.fulfill({contentType:'application/json',body:JSON.stringify(p)}).catch(()=>{});});
  await page.goto(`${base}/#reports`);await ready('weekly');assert.equal(await page.locator('#twweekly-Rows .tw-report-card').count(),20);await page.locator('#twdaily-Reload').click();await ready('daily');assert.equal(started,2);release();assert.match(await page.locator('#twdaily-Rows').innerText(),/WARMING_UP/);await page.locator('[data-reports-page=us]').click();await page.waitForFunction(()=>document.getElementById('reportsStatus').textContent.includes("READY"));assert.equal(await page.locator('#twReports-daily').isVisible(),false);assert.equal(await page.locator('#twReportDetail').evaluate(n=>n.open),false);
});
for(const type of ['daily','weekly'])test(`${type} rapid next/previous uses newest matching page and leave cancels pending rendering`,async()=>{
  await open();await page.locator(`[data-reports-page=tw-${type}]`).click();await ready(type);let release;const held=new Promise(r=>release=r);await page.route('**/api/reports/tw?*',async r=>{const u=new URL(r.request().url());if(u.searchParams.get('offset')==='20')await held;await r.fulfill({contentType:'application/json',body:JSON.stringify(twReportsFixture(u))}).catch(()=>{});});await page.locator(`#tw${type}-Next`).click();await page.waitForFunction(type=>document.getElementById(`tw${type}-Status`).textContent.includes('Loading'),type);await page.locator(`#tw${type}-Previous`).click();await ready(type);release();assert.match(await page.locator(`#tw${type}-Page`).innerText(),/offset 0/);assert.equal(await page.locator(`#tw${type}-Rows .tw-report-card`).count(),20);
  let leave;const pending=new Promise(r=>leave=r);await page.route('**/api/reports/tw?*',async r=>{await pending;await r.fulfill({contentType:'application/json',body:JSON.stringify(twReportsFixture(new URL(r.request().url())))}).catch(()=>{});});await page.locator(`#tw${type}-Reload`).click();await page.evaluate(()=>location.hash='overview');await page.waitForFunction(()=>document.getElementById('reportsView').hidden);leave();assert.equal(await page.locator(`#tw${type}-Rows .tw-report-card`).count(),0);
});
test('detail A then B, pending refresh newest request, Escape and leave never accept late body',async()=>{
  await open();await page.locator('[data-reports-page=tw-daily]').click();await ready('daily');let release,n=0;const held=new Promise(r=>release=r);await page.route('**/api/reports/tw/detail?*',async r=>{const first=++n===1;if(first)await held;const p=twDetailFixture(new URL(r.request().url()));p.report.markdown=first?'OLD BODY':'NEW BODY';await r.fulfill({contentType:'application/json',body:JSON.stringify(p)}).catch(()=>{});});
  await page.locator('.tw-report-open').first().click();await page.waitForFunction(()=>document.getElementById('twReportStatus').textContent.includes('Loading'));await page.locator('#twReportReload').click();await detail();assert.equal(n,2);assert.equal(await page.locator('#twReportBody').innerText(),'NEW BODY');
  // Exercise the same opener path while the modal is open, without forcing a browser click through the backdrop.
  await page.locator('#twdaily-Rows .tw-report-open').nth(1).evaluate(n=>n.click());await detail();release();assert.equal(await page.locator('#twReportBody').innerText(),'NEW BODY');await page.keyboard.press('Escape');assert.equal(await page.locator('#twdaily-Rows .tw-report-open').nth(1).evaluate(n=>n===document.activeElement),true);
  let leave;const pending=new Promise(r=>leave=r);await page.route('**/api/reports/tw/detail?*',async r=>{await pending;await r.fulfill({contentType:'application/json',body:JSON.stringify(twDetailFixture(new URL(r.request().url())))}).catch(()=>{});});await page.locator('.tw-report-open').first().click();await page.evaluate(()=>location.hash='overview');await page.waitForFunction(()=>!document.getElementById('twReportDetail').open);leave();assert.equal(await page.locator('#twReportBody').textContent(),'');
});
