import {test,before,after,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {serveStaticAsset} from './static-assets.mjs';
import {twFixture,warmingFixture} from './tw-stocks-fixture.mjs';
const {chromium}=createRequire(import.meta.url)('playwright');
let browser,server,base,page,errors,requests;
before(async()=>{server=createServer(serveStaticAsset);await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});});
after(async()=>{await browser.close();await new Promise(r=>server.close(r));});
beforeEach(async()=>{page=await browser.newPage();errors=[];requests=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',r=>{const u=new URL(r.request().url());requests.push(u);const p=u.pathname==='/api/tw/stocks'?twFixture(u.searchParams.get('date')):u.pathname==='/api/history'?{from:u.searchParams.get('from'),to:u.searchParams.get('to'),jobs:[]}:u.pathname==='/api/runner/executions'?{status:'NOT_CONFIGURED',jobs:[],warnings:[]}:u.pathname==='/api/settings/job-metadata'?{version:1,revision:'0',overrides:{},warning:null}:{collectionStatus:'NOT_CONFIGURED',collectedAt:new Date().toISOString(),jobs:[],errors:[],warnings:[],unmatchedIncludes:[]};return r.fulfill({contentType:'application/json',body:JSON.stringify(p)});});});
afterEach(async()=>{await page.close();assert.deepEqual(errors,[]);});
const ready=()=>page.waitForFunction(()=>!document.getElementById('twStatus').textContent.startsWith('Loading') && document.getElementById('twStatus').textContent.length>0);
const open=async(width=1280)=>{await page.setViewportSize({width,height:900});await page.goto(`${base}/#tw`);await ready();};
const count=()=>requests.filter(u=>u.pathname==='/api/tw/stocks').length;
for(const width of [1280,375,320])test(`actual TW facts/Tab Space Escape, safe text and no overflow at ${width}`,async()=>{
  await page.route('**/api/tw/stocks',r=>{requests.push(new URL(r.request().url()));const p=twFixture(null,'PARTIAL');p.observation.candidates[0].stockName='<img src=x onerror=globalThis.twPwned=true> C:\\secret\\db';return r.fulfill({contentType:'application/json',body:JSON.stringify(p)});});await open(width);
  assert.match(await page.locator('#twStatus').innerText(),/PARTIAL/);assert.equal(await page.locator('.tw-candidate').count(),1);assert.match(await page.locator('#twDaily').innerText(),/Latest attempt[\s\S]*Latest finalized/);assert.match(await page.locator('#twWeekly').innerText(),/FAILED[\s\S]*INDEPENDENT/);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);
  let found=false;for(let n=0;n<100;n++){await page.keyboard.press('Tab');found=await page.evaluate(()=>document.activeElement?.classList.contains('tw-candidate-open'));if(found)break;}assert.ok(found);assert.equal(await page.locator('.tw-candidate-open').evaluate(n=>getComputedStyle(n).outlineStyle!=='none'),true);
  await page.keyboard.press('Space');assert.equal(await page.locator('#twCandidateDetail').evaluate(n=>n.open),true);assert.equal(await page.locator('#twCandidateClose').evaluate(n=>n===document.activeElement),true);assert.match(await page.locator('#twCandidateBody').innerText(),/Anomaly score · 來源異常分數[\s\S]*SUCCESS[\s\S]*不能解讀為分析完成/);
  assert.equal(await page.locator('#twView img,#twView script,#twCandidateDetail img').count(),0);assert.equal(await page.evaluate(()=>globalThis.twPwned),undefined);assert.doesNotMatch(await page.locator('#twView').innerText(),/secret|投資分數|buy score/i);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);
  await page.keyboard.press('Escape');assert.equal(await page.locator('.tw-candidate-open').evaluate(n=>n===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#twCandidateDetail').evaluate(n=>n.open),true);await page.keyboard.press('Escape');
});
test('zero WARMING_UP newer failed attempt and missing journal unknown never become no anomaly or zero pending',async()=>{
  await page.route('**/api/tw/stocks',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(warmingFixture())}));await open();assert.match(await page.locator('#twCandidates').innerText(),/0 個候選[\s\S]*WARMING_UP[\s\S]*不能解讀為沒有異常/);assert.match(await page.locator('#twDaily').innerText(),/Latest attempt[\s\S]*FAILED[\s\S]*Latest finalized[\s\S]*PARTIAL/);assert.match(await page.locator('#twResponsibility').innerText(),/UNKNOWN[\s\S]*不能解讀為 0 項待辦/);assert.equal(await page.locator('.tw-candidate').count(),0);
});
test('valid scope survives no observation; independent weekly failed and readiness unavailable',async()=>{
  const p=twFixture(null,'PARTIAL');p.observation=null;p.latestFinalized=null;await page.route('**/api/tw/stocks',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(p)}));await open();assert.match(await page.locator('#twAccumulation').innerText(),/AVAILABLE[\s\S]*DAILY_ACCUMULATION[\s\S]*2026-09-21[\s\S]*Readiness UNAVAILABLE/);assert.match(await page.locator('#twWeekly').innerText(),/FAILED/);assert.equal(await page.locator('.tw-candidate').count(),0);
});
test('source unavailable / adapter error / HTTP failure clear stale sections and do not expose stderr',async()=>{
  await open();for(const state of ['UNAVAILABLE','ERROR']){await page.route('**/api/tw/stocks',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(twFixture(null,state))}));await page.locator('#twReload').click();await ready();assert.match(await page.locator('#twStatus').innerText(),new RegExp(state));assert.equal(await page.locator('.tw-candidate').count(),0);assert.equal(await page.locator('#twCandidateBody').innerText(),'');}
  await page.route('**/api/tw/stocks',r=>r.fulfill({status:503,body:'private stderr C:\\secret\\db'}));await page.locator('#twReload').click();await ready();assert.match(await page.locator('#twStatus').innerText(),/ERROR/);for(const id of ['twDaily','twSources','twCandidates','twResponsibility','twWeekly'])assert.equal(await page.locator(`#${id}`).innerText(),'');assert.doesNotMatch(await page.locator('#twView').innerText(),/private stderr|secret/);
});
test('exact date rejects invalid without request and Latest restores default',async()=>{
  await open();for(const bad of ['0000-01-01','2026-02-29','2026-9-25','--help']){await page.locator('#twDate').fill(bad);const n=count();await page.locator('#twFilter button[type=submit]').click();assert.match(await page.locator('#twValidation').innerText(),/真實日曆/);assert.equal(count(),n);}
  await page.locator('#twDate').fill('2026-09-25');await page.locator('#twFilter button[type=submit]').click();await ready();assert.match(await page.locator('#twProvenance').innerText(),/TARGET_DATE/);assert.equal(requests.filter(u=>u.pathname==='/api/tw/stocks').at(-1).searchParams.get('date'),'2026-09-25');await page.locator('#twLatest').click();await ready();assert.match(await page.locator('#twProvenance').innerText(),/LATEST_FINALIZED/);assert.equal(requests.filter(u=>u.pathname==='/api/tw/stocks').at(-1).search,'');
});
test('refresh deduplication loading clears stale, first visit once, no automatic polling or return-navigation calls',async()=>{
  await open();assert.equal(count(),1);await page.locator('#overviewPage').click();await page.locator('#twPage').click();assert.equal(count(),1);let release;const held=new Promise(r=>release=r);await page.route('**/api/tw/stocks',async r=>{requests.push(new URL(r.request().url()));await held;await r.fulfill({contentType:'application/json',body:JSON.stringify(twFixture())});});
  await page.locator('#twReload').click();await page.waitForFunction(()=>document.getElementById('twStatus').textContent.startsWith('Loading'));assert.equal(await page.locator('.tw-candidate').count(),0);await page.locator('#twReload').click();assert.equal(count(),2);release();await ready();await page.waitForTimeout(1300);assert.equal(count(),2);
});
test('newer exact date wins and leaving cancels old response rendering',async()=>{
  await open();let release;const held=new Promise(r=>release=r);await page.route('**/api/tw/stocks*',async r=>{const u=new URL(r.request().url());requests.push(u);if(!u.search)await held;const p=twFixture(u.searchParams.get('date'));p.observation.candidates[0].stockName=u.search?'FRESH RESPONSE':'OLD RESPONSE';await r.fulfill({contentType:'application/json',body:JSON.stringify(p)}).catch(()=>{});});await page.locator('#twReload').click();await page.waitForFunction(()=>document.getElementById('twStatus').textContent.startsWith('Loading'));await page.locator('#twDate').fill('2026-09-25');await page.locator('#twFilter button[type=submit]').click();await ready();release();assert.match(await page.locator('#twCandidates').innerText(),/FRESH RESPONSE/);assert.doesNotMatch(await page.locator('#twCandidates').innerText(),/OLD RESPONSE/);
  await page.unroute('**/api/tw/stocks*');let leave;const wait=new Promise(r=>leave=r);await page.route('**/api/tw/stocks*',async r=>{await wait;await r.fulfill({contentType:'application/json',body:JSON.stringify(twFixture('2026-09-25'))}).catch(()=>{});});await page.locator('#twReload').click();await page.waitForFunction(()=>document.getElementById('twStatus').textContent.startsWith('Loading'));await page.locator('#overviewPage').click();leave();assert.equal(await page.locator('.tw-candidate').count(),0);
});
test('saved baseline/mapping/source unknown/truncated pending distinctions remain visible',async()=>{
  const p=twFixture(null,'PARTIAL');p.observation.baselineSessionDiagnostics.state='LEGACY_DIAGNOSTICS_UNAVAILABLE';p.observation.baselineSessionDiagnostics.records=[];p.observation.mappingDiagnostics.unmappedSymbols=['9999'];p.observation.sources[0].status='PARTIAL';p.responsibility.state='PARTIAL';p.responsibility.truncated=true;p.responsibility.pendingCount=null;p.responsibility.unfinishedCount=null;await page.route('**/api/tw/stocks',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(p)}));await open();assert.match(await page.locator('#twAccumulation').innerText(),/LEGACY_DIAGNOSTICS_UNAVAILABLE[\s\S]*Unmapped symbols · 不是候選[\s\S]*9999/);assert.match(await page.locator('#twSources').innerText(),/PARTIAL/);assert.match(await page.locator('#twResponsibility').innerText(),/UNKNOWN[\s\S]*Truncated[\s\S]*true/);assert.equal(await page.locator('.tw-candidate').count(),1);
});
