/* Static design prototype. No network, filesystem or production API access. */
const NAV = [
  ['overview','Overview','◫'],['automations','Automations','◇'],['us','US Stocks','▤'],
  ['tw','TW Stocks','▦'],['performance','Performance','◷'],['reports','Reports','▧'],
  ['evidence','Data & Evidence','◎'],['settings','Settings','⚙']
];
const TABS = {
  automations:['Today','History','Schedule','Evidence'],
  us:['Signals','SEC Transactions','Ticker Detail'],
  tw:['Daily Scan','Accumulation','Candidates'],
  performance:['Summary','Signal Detail'],
  reports:['All','US Insider','TW Daily','TW Weekly'],
  evidence:['Data Sources','Schedule Versions','Correlation','Runner'],
  settings:['Job Display','Data Sources','Refresh','Default View','Appearance']
};
const state={page:'overview',tabs:{},signalView:'cards',signalFilter:'All',query:'',horizon:'1M',selectedReport:'All',drawerReturn:null};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const badge=(label,tone='')=>`<span class="badge ${tone}">${esc(label)}</span>`;
const detail=(label,value)=>`<div class="detail-line"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;
const panel=(title,body,sub='',action='')=>`<section class="panel"><div class="panel-head"><div><div class="panel-title">${title}</div>${sub?`<div class="panel-sub">${sub}</div>`:''}</div>${action}</div>${body}</section>`;
const metric=(label,value,note,icon)=>`<div class="card metric"><div class="metric-top"><span>${label}</span><span class="metric-icon">${icon}</span></div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`;
const table=(heads,rows)=>`<div class="table-wrap"><table class="data-table"><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const row=cells=>`<tr>${cells.map(c=>`<td>${c}</td>`).join('')}</tr>`;
const button=(label,act,id,cls='row-button')=>`<button type="button" class="${cls}" data-action="${act}" data-id="${esc(id)}">${label}</button>`;
const signals=[
  {id:'us-1',ticker:'DEMO',company:'Northstar Labs',source:'AI Report',date:'Sep 28',score:'92',investment:'87',buyers:'3 buyers',amount:'$1.8M',discovered:'Sep 28 · 10:42',status:'Active',review:'None',p1d:'+2.4%',p1w:'—',p1m:'—'},
  {id:'us-2',ticker:'ATLS',company:'Atlas Components',source:'SEC',date:'Sep 27',score:'—',investment:'—',buyers:'1 buyer',amount:'$420K',discovered:'Sep 28 · 11:15',status:'Review',review:'Amendment',p1d:'—',p1w:'—',p1m:'—'},
  {id:'us-3',ticker:'NOVA',company:'Nova Bio Research',source:'AI Report',date:'Sep 26',score:'84',investment:'79',buyers:'2 buyers',amount:'$760K',discovered:'Sep 27 · 10:40',status:'Active',review:'None',p1d:'+0.8%',p1w:'+4.1%',p1m:'—'}
];
const transactions=[
  {id:'tx-1',ticker:'ATLS',issuer:'Atlas Components',insider:'A. Chen',type:'P · Open market',shares:'12,000',price:'$35.00',amount:'$420K',filing:'Sep 28',form:'4/A',flags:'Amendment review'},
  {id:'tx-2',ticker:'DEMO',issuer:'Northstar Labs',insider:'M. Rivera',type:'P · Open market',shares:'8,000',price:'$48.25',amount:'$386K',filing:'Sep 28',form:'4',flags:'—'},
  {id:'tx-3',ticker:'NOVA',issuer:'Nova Bio Research',insider:'J. Park',type:'A · Award',shares:'4,000',price:'—',amount:'—',filing:'Sep 27',form:'4',flags:'Non-purchase'}
];
const jobs=[['Market data','06:30','06:31','Succeeded','good'],['SyncImport','10:40','10:42','Succeeded','good'],['SEC collector','11:15','11:17','Succeeded','good'],['TW daily scan','14:30','14:32','Succeeded','good'],['TW daily scan','17:00','—','Next','']];
const reports=[['Sep 28','US Insider','3','Imported','0','r2'],['Sep 28','TW Daily','6','Partial','2','—'],['Sep 27','TW Weekly','—','Ready','1','r1']];
function renderNav(){for(const id of ['side-nav','mobile-nav']) $(id).innerHTML=NAV.map(([key,label,icon])=>`<button type="button" class="nav-item" data-action="navigate" data-id="${key}" ${state.page===key?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</button>`).join('')}
function heading(title,subtitle,status='DESIGNED'){return `<div class="page-head"><div><span class="eyebrow">${status} · PRODUCT SPACE</span><h1>${title}</h1><p>${subtitle}</p></div><div class="head-meta"><strong>Design preview · Sep 28, 2026</strong>Illustrative local data</div></div><div class="status-legend"><strong>SAMPLE / PROTOTYPE DATA.</strong> The entries and values on this page are illustrative. Capability labels describe the reviewed code baseline, not a live connection.</div>`}
function tabs(page){const active=state.tabs[page]||TABS[page][0];return `<div class="tabs" role="tablist" aria-label="${NAV.find(n=>n[0]===page)[1]} 子頁">${TABS[page].map(t=>`<button type="button" class="tab" role="tab" aria-selected="${active===t}" data-action="tab" data-id="${esc(t)}">${esc(t)}</button>`).join('')}</div>`}
function sourceRow(name,time,tone,label){return `<div class="source-row"><div><strong>${name}</strong><small>${time}</small></div>${badge(label,tone)}</div>`}
function overview(){return heading('Good morning, Neil','One place to understand your automations and research data.','DESIGNED')+
  `<div class="grid metrics">${metric('Automation','4 / 5','<b>4 observed OK</b> · 1 upcoming','◇')}${metric('US Signals','3 new','Source integration · designed','↗')}${metric('TW Signals','6 new','Source integration · designed','▦')}${metric('Attention','1','TW source coverage · partial','!')}</div>`+
  `<div class="grid overview-grid"><div class="grid">${panel("Today's pipeline",`<div class="pipeline">${jobs.map((j,i)=>`<div class="pipeline-row"><span class="step ${i===4?'future':''}">${i===4?'○':'✓'}</span><strong>${j[0]}</strong><span class="pipeline-time">${j[1]}</span>${badge(j[3],j[4])}</div>`).join('')}</div>`,'Scheduler + Runner · illustrative',button('Automations →','navigate','automations','small-link'))}
  ${panel("Today's findings",`<div class="split-findings"><div class="finding"><span class="market">US STOCKS</span><strong>3 new signals</strong><p>AI reports and SEC activity, each with separate provenance and review flags.</p><div class="finding-foot"><span>Insider Tracker · sample</span>${button('View signals →','navigate','us','small-link')}</div></div><div class="finding"><span class="market">TW STOCKS</span><strong>6 observations</strong><p>Daily scan is partial. Source coverage is shown before candidate counts.</p><div class="finding-foot"><span>AIStockHunter · sample</span>${button('View scan →','navigate','tw','small-link')}</div></div></div>`,'Normalized feeds · future integration')}
  </div><div class="right-stack">${panel('Data freshness',`<div class="source-list">${sourceRow('SEC filings','Observed 11:15 · daily policy','good','Fresh')}${sourceRow('Market prices','Observed 06:30 · session policy','good','Fresh')}${sourceRow('AI Reports','Imported 10:42 · daily policy','good','Fresh')}${sourceRow('TW daily scan','Observed 14:32 · coverage incomplete','warn','Partial')}</div>`,'Task success does not prove data completeness',button('All sources →','navigate','evidence','small-link'))}
  ${panel('Recent reports',reports.map(r=>`<div class="report-row"><span class="report-date">${r[0]}</span><span><strong>${r[1]}</strong><small>${r[2]} signals · ${r[3]}</small></span>${badge(r[5],r[3]==='Partial'?'warn':'good')}</div>`).join(''),'Report records · illustrative',button('Reports →','navigate','reports','small-link'))}</div></div>`}
function automations(){let t=state.tabs.automations||'Today';let content='';
 if(t==='Today')content=`<div class="grid metrics">${metric('Observed today','4','Completed Scheduler observations','✓')}${metric('Running','0','No active observation','◷')}${metric('Next scheduled','17:00','TW daily scan · Asia/Taipei','→')}${metric('Runner coverage','4 / 4','Receipts on observed executions','◎')}</div>${panel('Workflow · research pipeline',`<div class="pipeline">${jobs.map((j,i)=>`<div class="pipeline-row"><span class="step ${i===4?'future':''}">${i===4?'○':'✓'}</span><strong>${j[0]}</strong><span class="pipeline-time">${j[1]}</span>${badge(j[3],j[4])}</div>`).join('')}</div>`,'Existing workflow/grouping concept · DONE')}`;
 if(t==='History')content=`${panel('Observed executions · 7 days',table(['Job','Day','Scheduled','Observed','Outcome','Evidence'],[['Market data','Sep 28','06:30','06:31','Succeeded','Scheduler + Runner'],['TW daily scan','Sep 27','17:00','17:03','Failed','Runner receipt'],['SEC collector','Sep 27','11:15','11:18','Succeeded','Scheduler']].map(x=>row([`<strong>${x[0]}</strong>`,...x.slice(1,4),badge(x[4],x[4]==='Failed'?'bad':'good'),x[5]]))),'Existing 7-day history · DONE · 30D/90D planned')}<p class="note-line">A failed execution stays an executed failure. This page does not generate MISSED.</p>`;
 if(t==='Schedule')content=`<div class="grid two-col">${panel('異常成交量每日掃描',`${detail('Current version','v3 · sample')}${detail('Enabled','Yes')}${detail('Timezone','Asia/Taipei')}${detail('Triggers','Mon–Fri 14:30, 17:00')}${detail('First observed','Sep 12 · 09:02')}${detail('Last observed','Sep 28 · 14:31')}`,'Stage A repository · BACKEND_READY')}${panel('Version history',`<div class="timeline"><div class="timeline-item"><strong>v3 · current</strong><small>Sep 12–Sep 28 · two weekday triggers</small></div><div class="timeline-item"><strong>Observation gap</strong><small>Sep 10–11 · schedule state uncertain</small></div><div class="timeline-item"><strong>v2 · previous</strong><small>Aug 26–Sep 09 · one weekday trigger</small></div></div>`,'An observation gap never proves a missed run')}</div>`;
 if(t==='Evidence')content=`<div class="notice">Occurrence correlation is shadow diagnostic evidence. Research tolerances are not Windows Scheduler provenance; no production MISSED is displayed.</div><div class="grid two-col">${panel('17:02 execution',`${detail('Scheduler','Observed')}${detail('Runner','Observed · trusted mapping')}${detail('Occurrence','17:00')}${detail('Correlation','CORRELATED')}`,'Stage B · shadow only')}${panel('16:58 candidate',`${detail('14:30','Late candidate')}${detail('17:00','Early candidate')}${detail('Correlation','AMBIGUOUS')}${detail('Selected occurrence','—')}`,'Competing triggers retained')}</div>`;
 return heading('Automations','Your workflow, schedule and execution evidence in one place.',t==='Schedule'||t==='Evidence'?'BACKEND_READY':'DONE')+tabs('automations')+content}
function signalCards(){let data=filteredSignals();if(!data.length)return `<div class="empty-box">No sample rows match this filter. Clear search or choose another source.</div>`;return `<div class="grid cards-3">${data.map(s=>`<article class="card signal-card"><div class="card-top"><div><div class="ticker">${s.ticker}</div><div class="card-desc">${s.company}</div></div><span class="score">Score ${s.score}</span></div><p>${s.source} · ${s.date}<br>${s.buyers} · ${s.amount}<br>Discovered ${s.discovered}</p><div class="mini-metrics"><span>1D<strong>${s.p1d}</strong></span><span>1W<strong>${s.p1w}</strong></span><span>1M<strong>${s.p1m}</strong></span><span style="margin-left:auto">${button('Details →','drawer',s.id)}</span></div></article>`).join('')}</div>`}
function filteredSignals(){return signals.filter(s=>(state.signalFilter==='All'||s.source===state.signalFilter)&&`${s.ticker} ${s.company}`.toLowerCase().includes(state.query.toLowerCase()))}
function us(){let t=state.tabs.us||'Signals';let content='';
 if(t==='Signals')content=`<div class="toolbar"><div class="filter-group">${['All','AI Report','SEC'].map(f=>button(f,'signal-filter',f,'chip')).join('')}</div><div class="filter-group"><input class="search" id="signal-search" type="search" placeholder="Search ticker or company" aria-label="Search sample signals" value="${esc(state.query)}"><div class="segmented">${button('Cards','signal-view','cards')}${button('Table','signal-view','table')}</div></div></div><div id="signal-results">${state.signalView==='cards'?signalCards():signalTable()}</div><p class="note-line">Scores, buyer counts, purchase amount and performance remain — when the source does not supply them. Prototype values are illustrative.</p>`;
 if(t==='SEC Transactions')content=`${panel('SEC transaction records',table(['Ticker','Issuer','Insider','Type','Shares','Price','Amount','Filing','Form','Review'],transactions.map(x=>row([button(x.ticker,'drawer',x.id),x.issuer,x.insider,x.type,x.shares,x.price,x.amount,x.filing,x.form,badge(x.flags,x.flags==='—'?'':'warn')]))),'Source records · DATA_READY; normalized listing · DESIGNED')}<p class="note-line">Form 4/A and review flags remain visible. Reconciliation is unresolved and not implied by this sample view.</p>`;
 if(t==='Ticker Detail')content=`<div class="grid two-col">${panel('DEMO · Northstar Labs',`${detail('Latest signal','Sep 28 · AI Report')}${detail('SEC records','1 linked only by explicit source ref')}${detail('Report reference','report:2026-09-28:DEMO')}${detail('1M performance','— · pending')}`,'Ticker aggregate · PLANNED')}${panel('Research timeline',`<div class="timeline"><div class="timeline-item"><strong>Sep 28 · Report imported</strong><small>Score 92 · illustrative</small></div><div class="timeline-item"><strong>Sep 28 · SEC record</strong><small>Source identity preserved separately</small></div></div>`,'Never join by ticker/date alone')}</div>`;
 return heading('US Stocks','Signals, filings and company context with source-level provenance.',t==='Signals'?'DATA_READY':'DESIGNED')+tabs('us')+content}
function signalTable(){let d=filteredSignals();if(!d.length)return `<div class="empty-box">No sample rows match this filter.</div>`;return table(['Ticker','Source','Date','AI score','Investment','Buyers','Amount','Discovered','Review','1M'],d.map(s=>row([button(s.ticker,'drawer',s.id),s.source,s.date,s.score,s.investment,s.buyers,s.amount,s.discovered,badge(s.review,s.review==='None'?'good':'warn'),s.p1m])))}
function tw(){let t=state.tabs.tw||'Daily Scan';let content='';
 if(t==='Daily Scan')content=`<div class="grid metrics">${metric('Scan state','PARTIAL','Coverage incomplete','!')}${metric('Observed','6','Source-issued observations','▤')}${metric('Eligible','2','Explicit source flag only','✓')}${metric('Run date','Sep 28','Asia/Taipei · sample','◷')}</div>${panel('Daily scan',table(['Symbol','Classification','Anomaly score','Volume ratio','Coverage','Eligibility','Warning'],[['TEST1','Unexplained','82','3.4×','Complete','Eligible','—'],['TEST2','Watch','67','2.1×','Partial','Review','Official source gap'],['TEST3','Explained','45','1.6×','Complete','No','—']].map(x=>row([`<strong>${x[0]}</strong>`,x[1],x[2],x[3],badge(x[4],x[4]==='Partial'?'warn':'good'),x[5],x[6]]))),'AIStockHunter private output → future normalized export')}`;
 if(t==='Accumulation')content=`<div class="grid two-col">${panel('Accumulation scope',`${detail('Start date','Sep 01 · sample')}${detail('Latest target','Sep 28')}${detail('Day state','PARTIAL')}${detail('Market observations','5 / 6 sources')}`,'Status reflects source coverage')}${panel('Source coverage',`${sourceRow('Daily accumulation','Sep 28 · finished 14:37','warn','PARTIAL')}${sourceRow('Official filings','Sep 28 · observed 14:35','good','READY')}${sourceRow('Intraday odd lots','Sep 28 · missing session','warn','UNKNOWN')}`,'No inferred completeness')}</div>`;
 if(t==='Candidates')content=`<div class="notice">Candidates are shown only when an active source contract explicitly labels them. Legacy strategy rows are not treated as the daily accumulation candidate feed.</div>${panel('Explicit source candidates',table(['Symbol','Signal date','Basis','Score','Eligibility','Evidence'],[['TEST1','Sep 28','Unexplained volume','82','Eligible','3 source refs'],['TEST2','Sep 28','Coverage limited','—','Review','Missing official data']].map(x=>row(x))),'Normalized candidate export · DESIGN ONLY')}`;
 return heading('TW Stocks','Daily scans, accumulation and candidate evidence with honest coverage.',t==='Daily Scan'?'DATA_READY':'DESIGNED')+tabs('tw')+content}
function performance(){let t=state.tabs.performance||'Summary';let content=`<div class="toolbar"><div class="filter-group">${['1D','1W','1M','3M','6M'].map(h=>button(h,'horizon',h,'chip')).join('')}</div><span class="note-line">Selected horizon: ${state.horizon} · pending observations remain —</span></div>`;
 if(t==='Summary')content+=`<div class="grid metrics">${metric('Observed','8 / 12','4 pending · sample','◷')}${metric('Win rate','62.5%','Observed signals only','↗')}${metric('Average return','+3.8%','Observed signals only','%')}${metric('Max drawdown','—','Read-only detail contract needed','↓')}</div>${panel('By score bucket',table(['Bucket','Signals','Observed','Win rate','Average return','Max upside','Max adverse','Days to peak'],[['80–100','6','4','75%','+5.2%','—','—','—'],['60–79','6','4','50%','+2.4%','—','—','—']].map(x=>row(x))),'Current summary CLI is not approved for formal DB read-only use')}`;
 else content+=`<div class="grid two-col">${panel('DEMO · signal detail',`${detail('Entry basis','Next tradable session · sample')}${detail('Selected horizon',state.horizon)}${detail('Return',state.horizon==='1D'?'+2.4%':'— · pending')}${detail('Max upside','—')}${detail('Max adverse','—')}${detail('Max drawdown','—')}${detail('Days to peak','—')}${detail('First +10%','—')}${detail('First -10%','—')}`,'Source performance record · design')}${panel('Timeline',`<div class="timeline"><div class="timeline-item"><strong>Discovery</strong><small>Sep 28 · 10:42 · source report</small></div><div class="timeline-item"><strong>Next tradable</strong><small>Entry basis · sample</small></div><div class="timeline-item"><strong>${state.horizon} observation</strong><small>${state.horizon==='1D'?'Observed · sample':'Pending · no return asserted'}</small></div></div>`,'Do not replace missing sessions with 0%')}</div>`;
 return heading('Performance','Returns and excursions with explicit observation maturity.','DESIGNED')+tabs('performance')+content}
function reportsPage(){let t=state.tabs.reports||'All';let filtered=reports.filter(r=>t==='All'||r[1]===t);let content=`${panel('Report library',table(['Date','Type','Signals','Import state','Warnings','Revision',''],filtered.map((r,i)=>row([...r.slice(0,3),badge(r[3],r[3]==='Partial'?'warn':'good'),r[4],r[5],button('Open →','drawer',`report-${reports.indexOf(r)}`)]))),'Raw content and revisions require read-only source contracts')}<div class="section-label">REPORT DETAIL CONCEPT</div><div class="grid two-col">${panel('US Insider · Sep 28',`<div class="empty-box"><strong>Markdown report rendering</strong><br>Sanitized source Markdown would appear here after a read-only report adapter supplies the selected revision.</div>`,'No real Markdown is loaded in this prototype')}${panel('Revision history',`<div class="timeline"><div class="timeline-item"><strong>r2 · Sep 28 10:42</strong><small>Source hash and import time retained</small></div><div class="timeline-item"><strong>r1 · Sep 28 09:55</strong><small>Raw revision available in source</small></div></div><p class="note-line">A score/ticker diff is unavailable until the source provides a reliable comparison.</p>`,'Source revisions ≠ semantic diff')}</div>`;return heading('Reports','Source documents, import state and revision provenance.','DESIGNED')+tabs('reports')+content}
function evidence(){let t=state.tabs.evidence||'Data Sources';let content='';
 if(t==='Data Sources')content=`<div class="grid two-col">${panel('Insider Tracker',`${detail('Availability','Sample available')}${detail('Contract','list-signals v1 · read-only')}${detail('Schema','v2 · sample')}${detail('Reports latest','Sep 28 · 10:42')}${detail('SEC latest','Sep 28 · 11:15')}${detail('Market latest','Sep 28 · 06:30')}`,'Actual integration · DESIGNED')}${panel('AIStockHunter',`${detail('Availability','Sample available')}${detail('Daily data','PARTIAL · Sep 28')}${detail('Weekly data','Sep 27')}${detail('Contract','Proposed normalized export v1')}`,'Current private outputs · DATA_READY')}${panel('Dashboard',`${detail('History DB','OK · sample')}${detail('Schedule history','Observed · sample')}${detail('Runner receipts','4 available · sample')}`,'Existing backend · DONE / BACKEND_READY')}${panel('Meaning of health',`<div class="empty-box">Task completion, source availability, data freshness and data completeness are separate observations. A successful Scheduler row does not turn incomplete source data into READY.</div>`,'Shared state model')}</div>`;
 if(t==='Schedule Versions')content=`${panel('Versioned schedule observations',table(['Job','Version','First observed','Last observed','Triggers','Gap'],[['TW daily scan','v3','Sep 12','Sep 28','14:30 · 17:00','Sep 10–11'],['SEC collector','v2','Sep 01','Sep 28','11:15','—']].map(x=>row([`<strong>${x[0]}</strong>`,...x.slice(1)]))),'Stage A · BACKEND_READY; no live UI/API')}`;
 if(t==='Correlation')content=`<div class="notice">Shadow research only. No automatic MISSED. Schedule-version gaps and ambiguous triggers retain their uncertainty.</div>${panel('Occurrence correlation',table(['Execution','Scheduler','Runner','Occurrence','State','Reason'],[['17:02','Observed','Observed','17:00','CORRELATED','Trusted mapping'],['16:58','Observed','Observed','—','AMBIGUOUS','Two trigger candidates'],['Sep 10','Observed','—','—','AMBIGUOUS_SCHEDULE_VERSION','Version gap']].map(x=>row([x[0],x[1],x[2],x[3],badge(x[4],x[4]==='CORRELATED'?'good':'warn'),x[5]]))),'Stage B shadow · BACKEND_READY')}`;
 if(t==='Runner')content=`<div class="grid metrics">${metric('Receipts','4','Observed today · sample','▤')}${metric('Coverage','100%','Of 4 observed jobs','◎')}${metric('Unmapped','0','Native IDs remain separate','◇')}${metric('Warnings','1','Historical unsupported episode','!')}</div>${panel('Runner evidence',table(['Native job ID','Mapped Dashboard job','Observed','Outcome','Coverage'],[['runner:tw-scan','\\Research\\TW Scan','14:32','Success','Receipt available'],['runner:sec','\\Research\\SEC Collector','11:17','Success','Receipt available']].map(x=>row(x))),'Mapping is trusted; IDs are never directly compared')}`;
 return heading('Data & Evidence','Trace each assessment back to its source and observation.','DESIGNED')+tabs('evidence')+content}
function settings(){let t=state.tabs.settings||'Job Display';let content='';
 if(t==='Job Display')content=`${panel('Display preferences',table(['Job','Display name','Market','Order','Visibility','Dependencies'],[['\\Research\\TW Scan','TW Daily Scan','TW','30','Visible','Market data'],['\\Research\\SEC Collector','SEC Collector','US','20','Visible','SyncImport']].map(x=>row(x))),'Existing editable job metadata · DONE')}<p class="note-line">Production settings include name, market, description, order, hidden, dependencies and reset. This prototype does not write settings.</p>`;
 if(t==='Data Sources')content=`<div class="grid two-col">${panel('Insider Tracker',`${detail('Path','Local configured path · masked')}${detail('Availability','Check only')}${detail('Contract','v1')}${detail('Access','Read-only')}`,'DESIGNED')}${panel('AIStockHunter',`${detail('Path','Local configured path · masked')}${detail('Availability','Check only')}${detail('Contract','Export v1 proposed')}${detail('Access','Read-only')}`,'DESIGNED')}</div>`;
 if(t==='Refresh')content=panel('Observation refresh policy',`${detail('Dashboard jobs','Manual view refresh · future')}${detail('External sources','Bounded cache · future')}${detail('Pipeline execution','Never from this page')}`,'DESIGNED; no action in static prototype');
 if(t==='Default View')content=panel('Landing page',`${detail('Default','Overview')}${detail('Other choice','Automations · future preference')}`,'DESIGNED');
 if(t==='Appearance')content=panel('Appearance',`${detail('Theme','Light concept')}${detail('Density','Comfortable')}${detail('Small screens','Responsive at 375px and 320px')}`,'DESIGNED');
 return heading('Settings','Presentation preferences and future read-only source configuration.',t==='Job Display'?'DONE':'DESIGNED')+tabs('settings')+content}
const PAGES={overview,automations,us,tw,performance,reports:reportsPage,evidence,settings};
function render(){renderNav();const item=NAV.find(n=>n[0]===state.page);$('top-section').textContent=item[1];$('main').innerHTML=PAGES[state.page]();document.querySelectorAll('[data-action="signal-filter"]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===state.signalFilter)));document.querySelectorAll('[data-action="signal-view"]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===state.signalView)));document.querySelectorAll('[data-action="horizon"]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===state.horizon)));}
function openDrawer(id){let title='',subtitle='',body='';let s=signals.find(x=>x.id===id),tx=transactions.find(x=>x.id===id);if(s){title=`${s.ticker} · ${s.company}`;subtitle=`${s.source} · ${s.date}`;body=`<div class="drawer-section"><h3>Signal</h3>${detail('AI score',s.score)}${detail('Investment score',s.investment)}${detail('Buyers',s.buyers)}${detail('Purchase amount',s.amount)}${detail('Active state',s.status)}${detail('Review',s.review)}${detail('Discovered',s.discovered)}</div><div class="drawer-section"><h3>Performance</h3>${detail('1D',s.p1d)}${detail('1W',s.p1w)}${detail('1M',s.p1m)}</div><p class="note-line">Sample values. Missing source data remains —.</p>`}else if(tx){title=`${tx.ticker} · ${tx.insider}`;subtitle=`${tx.issuer} · ${tx.form}`;body=`<div class="drawer-section"><h3>Transaction</h3>${detail('Type',tx.type)}${detail('Shares',tx.shares)}${detail('Price',tx.price)}${detail('Amount',tx.amount)}</div><div class="drawer-section"><h3>Filing & owner</h3>${detail('Filing date',tx.filing)}${detail('Form',tx.form)}${detail('Reporting owner',tx.insider)}${detail('Review flags',tx.flags)}${detail('Source metadata','Accession retained · sample')}</div><p class="note-line">Amendment reconciliation is not asserted.</p>`}else if(id.startsWith('report-')){let r=reports[Number(id.slice(7))];if(!r)return;title=`${r[1]} · ${r[0]}`;subtitle=`Revision ${r[5]} · ${r[3]}`;body=`<div class="drawer-section"><h3>Metadata</h3>${detail('Signals',r[2])}${detail('Import state',r[3])}${detail('Warnings',r[4])}${detail('Revision',r[5])}</div><div class="drawer-section"><h3>Source content</h3><div class="empty-box">A sanitized Markdown rendering would appear here once a read-only source contract is implemented.</div></div>`}else return;
 $('drawer-body').innerHTML=`<h2 id="drawer-title">${esc(title)}</h2><p>${esc(subtitle)}</p>${body}`;$('drawer').hidden=false;$('drawer-backdrop').hidden=false;state.drawerReturn=document.activeElement;$('drawer-close').focus();}
function closeDrawer(){$('drawer').hidden=true;$('drawer-backdrop').hidden=true;state.drawerReturn?.focus();}
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(!b)return;let a=b.dataset.action,id=b.dataset.id;if(a==='navigate'){state.page=id;history.replaceState(null,'',`#${id}`);render();$('main').focus();window.scrollTo(0,0)}else if(a==='tab'){state.tabs[state.page]=id;render();document.querySelector('.tab[aria-selected="true"]')?.focus()}else if(a==='signal-filter'){state.signalFilter=id;render()}else if(a==='signal-view'){state.signalView=id;render()}else if(a==='horizon'){state.horizon=id;render()}else if(a==='drawer')openDrawer(id)});
document.addEventListener('input',e=>{if(e.target.id==='signal-search'){state.query=e.target.value;$('signal-results').innerHTML=state.signalView==='cards'?signalCards():signalTable()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('drawer').hidden)closeDrawer();if(e.target.matches('[role="tab"]')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let all=[...document.querySelectorAll('[role="tab"]')],i=all.indexOf(e.target),next=e.key==='Home'?0:e.key==='End'?all.length-1:(i+(e.key==='ArrowRight'?1:-1)+all.length)%all.length;all[next].click()}});
$('drawer-close').addEventListener('click',closeDrawer);$('drawer-backdrop').addEventListener('click',closeDrawer);
let initial=location.hash.slice(1);if(PAGES[initial])state.page=initial;render();
